### ISSUE TITLE
Stockstatus on productpage

### ISSUE THREAD

**Issue by Mic2005** [jeroenvermeulen/jeroenvermeulen-blockcache#3]
Jeroen, we use Amasty Custom Stock Status extension in Magento 1.7.0.2 but I want to know if your extension flush productpage cache when product is sold and Amasty change the stockstatus from "One Day" to "14 days". When we used Lesti::FPC the stock did not change after placing the order.
Can you tell me more about this? Do i need to add custom class?

Regards, Micha

**Comment by jeroenvermeulen** [comment]
My extension can allow flushing a page from the cache, I does that by default.
It is configurable via `System > Configuration > ADVANCED > JeroenVermeulen BlockCache > Cache Flushes`
If you would allow all cache flushes the cache flushing should work like default Magento.
I would advise to test with the default settings first, since filtering certain flushes is better for performance.
